services:
  oss-projects:
    image: lucasrod96/oss-projects-hetzner-migration@sha256:3f2ea608b25c4420cde8a06b114b9c3519948dbd1e815b117b85b5d92ebcfed5
    container_name: oss-projects
    ports:
      - "8080:8080"
    platform: linux/amd64
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      - oss-projects
volumes:
  caddy_data:
  caddy_config:
