services:
  oss-projects:
    image: lucasrod96/oss-projects-hetzner-migration@sha256:23121fde54e7233d0f6b1f3ef41e77c1d75dc775cd405f7f42da4ddd90c9e63d
    container_name: oss-projects
    ports:
      - "8080:8080"
    platform: linux/amd64

  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      - oss-projects

volumes:
  caddy_data:
  caddy_config:
