clean:
    rm -rf .terraform*

init:
    terraform init

plan:
    terraform plan

apply:
    terraform apply --auto-approve

destroy:
    terraform destroy --auto-approve

validate:
    terraform validate

fmt:
    terraform fmt
