[build]
cmd = "make build-dev"
bin = "./bin/api"
include_dir = ["ui", "internal"]
exclude_dir = ["ui/node_modules", "ui/build"]
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "ts", "tsx"]

[proxy]
enabled = true
app_port = 8080
proxy_port = 8081
