services:
  oss-projects:
    image: lucasrod96/oss-projects:v0.1.5@sha256:c47f18e194ce13bc5f19cadd9a4d78663ed258a0f695483bf33052db4a04539e
    container_name: oss-projects
    platform: linux/amd64
  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      - oss-projects
volumes:
  caddy_data:
  caddy_config:
