---
- name: Configure oss-projects server
  hosts: hetzner_server
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: true

    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"

    - name: Install Docker using script
      shell: /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Verify Docker installation
      command: docker --version
      changed_when: false
