name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Unit Tests
        run: make test-unit

  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@7b53cdc2a387814ed14eec026287aac689ae8c9b # v2.1.9
        with:
          project_id: "groovy-momentum-434802-g9"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Adjust permissions of GCP credentials file
        # allows user in the docker container used by smoke tests to read the file
        run: chmod 644 "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Run Smoke Tests
        run: make test-smoke

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@7b53cdc2a387814ed14eec026287aac689ae8c9b # v2.1.9
        with:
          project_id: "groovy-momentum-434802-g9"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Adjust permissions of GCP credentials file
        # allows user in the docker container used by e2e tests to read the file
        run: chmod 644 "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Run E2E Tests
        run: make test-e2e

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node deps
        run: npm --prefix ui ci

      - name: Lint
        run: |
          if ! make lint; then
            echo "Linting failed. Try running \`make lint-fix\` to automatically resolve the linting errors."
            exit 1
          fi
