name: Write GitHub Data To Gist

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  write-to-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run CronJob
        run: go run cmd/cronjob/main.go
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

  notify-on-failure:
    needs: write-to-gist
    runs-on: ubuntu-latest
    if: ${{ !success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Send Notification Email
        run: go run cmd/sendemail/main.go
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
