name: Deploy Website

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run Tests
        run: make test-unit

      - name: Google Cloud Auth
        uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
        with:
          project_id: "groovy-momentum-434802-g9"
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy
        env:
          IMAGE_VERSION: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./scripts/deploy.sh

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes
